version: '3.2'
      
services:
  postgre:
    image: postgres
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:latest
    networks:
      - default
    ports:
      - 6381:6379
    
    
          
          

